technology: python
build_type: full
deployment: terraform

branching:
  strategy: semantic-versioning
  allowed_branches:
    - main
    - develop
    - release/*
    - hotfix/*

stages:
  lint: true
  static_analysis: true
  unit_tests: true
  integration_tests: true
  security_scan: true
  package_artifact: true
  deploy: true

deployment_target:
  environment: dev   # dev, staging, production
  cloud_provider: aws
  region: us-east-1
  service: lambda    # or ec2, ecs, eks
  deployment_method: sam # terraform, cdk, cloudformation, sam
