name: Generate and Push Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  generate-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Pipeline File from Blueprint or Template
        run: |
          python scripts/generate_pipeline.py

      - name: Commit and Push Changes if Needed
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config user.name "Nilesh234"
          git config user.email "ng.magare@tcs.com"
          git add generated_pipelines/
          git diff --cached --quiet || (git commit -m "Generated pipeline from blueprint or template" && git push origin main)
