name: Generate and Push Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'  # Ignore changes to workflows
      - 'generated_pipelines/**'  # Ignore generated pipeline files

permissions:
  contents: write
  id-token: write

jobs:
  generate-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up Git User
        run: |
          git config user.name "Nilesh234"
          git config user.email "ng.magare@tcs.com"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Pipeline File using Python script
        run: |
          python scripts/generate_pipeline.py

      - name: Commit and Push Changes if Needed
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          # Check if any generated pipeline files exist in the generated_pipelines folder
          GENERATED_PIPELINES=$(find generated_pipelines -type f -name "*.yml")
          
          if [ -n "$GENERATED_PIPELINES" ]; then
            # Add all generated pipeline files to git
            git add generated_pipelines/*.yml
            git diff --cached --quiet && echo "No changes to commit" || (
              git commit -m "Generated pipeline from blueprint"
              git push origin main
            )
          else
            echo "No generated pipeline files found, skipping commit."
          fi
