name: Generate Dynamic CI/CD Pipeline

permissions:
  contents: write  # 🛡️ Allow GitHub Actions bot to push commits

on:
  push:
    paths:
      - 'blueprint/**'
      - 'scripts/**'
      - 'templates/**'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11  # ✅ Modern Python version

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Generate Pipeline
      run: |
        python scripts/generate_pipeline.py

    - name: Configure Git for pushing
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

    - name: Commit and Push generated pipeline
      run: |
        git add -f .github/workflows/generated-pipeline.yml
        git commit -m "Generated pipeline from blueprint" || echo "No changes to commit"
        git push
