name: Generate Dynamic CI/CD Pipeline

on:
  push:
    paths:
      - 'blueprint/**'
      - 'scripts/**'
      - 'templates/**'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Generate Pipeline
      run: |
        python scripts/generate_pipeline.py

    - name: Commit generated pipeline
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add .github/workflows/generated-pipeline.yml
        git commit -m "Generated pipeline from blueprint" || echo "No changes"
        git push
